export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const GET_QUIZZES = "GET_QUIZZES";
export const GET_TEACHER_QUIZZES = "GET_TEACHER_QUIZZES";
export const GET_QUIZ = "GET_QUIZ";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";
export const EDIT_QUIZ_SUCCESS = "EDIT_QUIZ_SUCCESS";
export const EDIT_QUIZ_FAIL = "EDIT_QUIZ_FAIL";
export const DELETE_QUIZ = "DELETE_QUIZ";
export const ADD_QUIZ_QUESTION_SUCCESS = "ADD_QUIZ_QUESTION_SUCCESS";
export const ADD_QUIZ_QUESTION_FAIL = "ADD_QUIZ_QUESTION_FAIL";
export const DELETE_QUIZ_QUESTION_SUCCESS = "DELETE_QUIZ_QUESTION_SUCCESS";
export const DELETE_QUIZ_QUESTION_FAIL = "DELETE_QUIZ_QUESTION_FAIL";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_BY_QUIZ = "GET_QUESTIONS_BY_QUIZ";
export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";
export const EDIT_QUESTION_FAIL = "EDIT_QUESTION_FAIL";
export const DELETE_QUESTION = "DELETE_QUESTION"
export const GET_ANSWERS_BY_QUESTION_ID = "GET_ANSWERS_BY_QUESTION_ID";

export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAIL = "CREATE_ANSWER_FAIL";
export const EDIT_ANSWER_SUCCESS = "EDIT_ANSWER_SUCCESS";
export const EDIT_ANSWER_FAIL = "EDIT_ANSWER_FAIL";
export const DELETE_ANSWER = "DELETE_ANSWER";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const GET_ME_USER = "GET_ME_USER";
export const ENABLE_USER = "ENABLE_USER";

export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHER_COURSES = "GET_TEACHER_COURSES";
export const GET_CLASSROOM_STUDENTS = "GET_CLASSROOM_STUDENTS";
export const GET_CLASSROOMS = "GET_CLASSROOMS";
export const GET_CLASSROOM_BY_ID = "GET_CLASSROOM_BY_ID";
export const CREATE_CLASSROOM_SUCCESS = "CREATE_CLASSROOM_SUCCESS";
export const CREATE_CLASSROOM_FAIL = "CREATE_CLASSROOM_FAIL";
export const EDIT_CLASSROOM_SUCCESS = "EDIT_CLASSROOM_SUCCESS";
export const EDIT_CLASSROOM_FAIL = "EDIT_CLASSROOM_FAIL";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";
export const GET_CLASSROOM_COURSES = "GET_CLASSROOM_COURSES";
export const DELETE_CLASSROOM_COURSE = "DELETE_CLASSROOM_COURSE";
export const ADD_CLASSROOM_COURSE = "ADD_CLASSROOM_COURSE";

export const ASSIGN_QUIZ_SUCCESS = "ASSIGN_QUIZ_SUCCESS";
export const ASSIGN_QUIZ_FAIL = "ASSIGN_QUIZ_FAIL";

export const GET_COURSES = "GET_COURSES";
export const GET_STUDENT_CLASSROOM = "GET_STUDENT_CLASSROOM";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE_SUCCESS = "EDIT_COURSE_SUCCESS";
export const EDIT_COURSE_FAIL = "EDIT_COURSE_FAIL";

export const GET_USER_QUIZ_INSTANCES = "GET_USER_QUIZ_INSTANCES";
export const START_QUIZ_SUCCESS = "START_QUIZ_SUCCESS";
export const START_QUIZ_FAIL = "START_QUIZ_FAIL";
export const GET_QUIZ_INSTANCE = "GET_QUIZ_INSTANCE";
export const FINISH_QUIZ = "FINISH_QUIZ";
export const GET_FINISHED_QUIZ_INSTANCE = "GET_FINISHED_QUIZ_INSTANCE";

export const SAVE_ANSWER_OPTION_SUCCESS = "SAVE_ANSWER_OPTION_SUCCESS"
export const SAVE_ANSWER_OPTION_FAIL = "SAVE_ANSWER_OPTION_FAIL"

export const GET_COURSES_WITH_TEACHER_NAME = "GET_COURSES_WITH_TEACHER_NAME";
export const GET_TEACHERS_WITH_NAME = "GET_TEACHERS_WITH_NAME";
export const GET_STUDENTS_WITH_NAME = "GET_STUDENTS_WITH_NAME";

export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAIL = "CREATE_TEACHER_FAIL";
export const DELETE_TEACHER = "DELETE_TEACHER";
