export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const GET_QUIZZES = "GET_QUIZZES";
export const GET_QUIZ = "GET_QUIZ";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL";
export const EDIT_QUIZ_SUCCESS = "EDIT_QUIZ_SUCCESS";
export const EDIT_QUIZ_FAIL = "EDIT_QUIZ_FAIL";
export const DELETE_QUIZ = "DELETE_QUIZ";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_BY_QUIZ = "GET_QUESTIONS_BY_QUIZ";
export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";
export const EDIT_QUESTION_SUCCESS = "EDIT_QUESTION_SUCCESS";
export const EDIT_QUESTION_FAIL = "EDIT_QUESTION_FAIL";
export const DELETE_QUESTION = "DELETE_QUESTION"

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const GET_ME_USER = "GET_ME_USER";